/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DQTPanel.java
 *
 * Created on 22-Nov-2011, 21:22:43
 */
package image.jpeg.gui;

import image.gui.ImagePartPropertyPanel;
import image.jpeg.DQT;
import image.jpeg.DQT.Presision;
import image.jpeg.events.DQTTableModelEvent;
import javax.imageio.plugins.jpeg.JPEGQTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableColumn;

/**
 *
 * @author Dietmar
 */
public class DQTPanel extends ImagePartPropertyPanel {

    private Presision presision = Presision.PRESISION_8BIT;
    private JPEGQTable table = null;
    private TableHexEditor editor = new TableHexEditor(0xFF);

    /** Creates new form DQTPanel
     * @param table
     * @param presision  
     */
    public DQTPanel(JPEGQTable table, Presision presision) {
        initComponents();
        this.presision = presision;
        this.table = table;
        if (presision == DQT.Presision.PRESISION_16BIT) {
            editor = new TableHexEditor(0xFFFF);
        }
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            TableColumn col = jTable1.getColumnModel().getColumn(i);
            col.setCellEditor(editor);
        }
    }

    private class DQTTableModel extends javax.swing.table.AbstractTableModel {

        @Override
        public int getRowCount() {
            return 16;
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            if (presision == Presision.PRESISION_16BIT) {
                return String.format("0x%04X", table.getTable()[rowIndex * getColumnCount() + columnIndex]);
            } else {
                return String.format("0x%02X", table.getTable()[rowIndex * getColumnCount() + columnIndex]);
            }
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            if (((String) aValue).isEmpty()) {
                aValue = "0";
            }
            int[] values = table.getTable();
            int index = rowIndex * getColumnCount() + columnIndex;
            int value = Integer.parseInt((String) aValue, 16);
            values[index] = value;
            table = new JPEGQTable(values);
            fireTableChanged(new DQTTableModelEvent(this , columnIndex, rowIndex, table));
        }

        @Override
        public String getColumnName(int column) {
            return "";
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return true;
        }
    }

    /**
     * 
     * @param listener
     */
    public void addTableModelListener(TableModelListener listener) {
        jTable1.getModel().addTableModelListener(listener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new DQTTableModel());
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quantization table values");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
