/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusPanel.java
 *
 * Created on 19-Nov-2011, 21:29:21
 */
package donegalglitcher.gui;

import image.gui.ImageStatus;
import javax.swing.JPanel;

/**
 *
 * @author Dietmar
 */
public class StatusPanel extends JPanel implements ImageStatus {

    /** Creates new form StatusPanel */
    public StatusPanel() {
        initComponents();
    }

    /**
     * 
     * @param text
     */
    @Override
    public void setText(String text) {
        statusText.setText(text);
    }

    /**
     * 
     * @param current
     * @param min
     * @param max
     */
    @Override
    public void setProgress(long current, long min, long max) {
        statusProgress.setMinimum((int)min);
        statusProgress.setMaximum((int)max);
        statusProgress.setValue((int)current);
        statusProgress.setVisible(true);
    }
    
    /**
     * 
     * @param current
     */
    @Override
    public void setProgress(long current) {
        statusProgress.setValue((int)current);
    }
    /**
     * 
     * @param visible
     */
    @Override
    public void setProgressVisible(boolean visible) {
        statusProgress.setVisible(visible);
        invalidate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusText = new javax.swing.JLabel();
        statusProgress = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(32767, 20));
        setMinimumSize(new java.awt.Dimension(0, 20));
        setPreferredSize(new java.awt.Dimension(400, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusText, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(statusProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar statusProgress;
    private javax.swing.JLabel statusText;
    // End of variables declaration//GEN-END:variables
}
